service: status-service

custom:
  tableName: 'orders-table-${self:provider.stage}'
  queueName: 'OrderQueue'
  topicName: 'StatusTopic'
  dynamodb:
    start:
      migrate: true
    stages:
      - dev

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - sqs:*
            - sns:Publish
          Resource:
            - 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tableName}'
            - 'arn:aws:sqs:${self:provider.region}:*:${self:custom.queueName}'
            - 'arn:aws:sns:${self:provider.region}:*:${self:custom.topicName}'
  environment:
    NODE_ENV: dev
    ORDERS_TABLE: ${self:custom.tableName}
    ORDERS_QUEUE: ${self:custom.queueName}
    TOPIC_NAME: ${self:custom.topicName}
    ACCOUNT_ID: ${aws:accountId}

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

functions:
  status:
    handler: app/handler.status
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  queueHandler:
    handler: app/handler.queueHandler
    events:
      - sqs:
          arn:
            'arn:aws:sqs:${self:provider.region}:${aws:accountId}:${self:custom.queueName}'

resources:
  Resources:
    Topic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: '${self:custom.topicName}'
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: alakai.1998.28@gmail.com
        Protocol: email
        TopicArn: 'arn:aws:sns:${self:provider.region}:${aws:accountId}:${self:custom.topicName}'